export const DETECT_IMAGE_SUCCESS = 'DETECT_IMAGE_SUCCESS';
export const DETECT_IMAGE_LOADING = 'DETECT_IMAGE_LOADING';
export const DETECT_IMAGE_ERROR = 'DETECT_IMAGE_ERROR';

export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS';
export const POST_ITEM_LOADING = 'POST_ITEM_LOADING';
export const POST_ITEM_ERROR = 'POST_ITEM_ERROR';

export const GET_METADATA_SUCCESS = 'GET_METADATA_SUCCESS';
export const GET_METADATA_LOADING = 'GET_METADATA_LOADING';
export const GET_METADATA_ERROR = 'GET_METADATA_ERROR';

export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_LOADING = 'GET_ITEM_LOADING';
export const GET_ITEM_ERROR = 'GET_ITEM_ERROR';
