export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_LOADING = 'GET_PRODUCT_DETAIL_LOADING';
export const GET_PRODUCT_DETAIL_ERROR = 'GET_PRODUCT_DETAIL_ERROR';

export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_LOADING = 'POST_LIKE_LOADING';
export const POST_LIKE_ERROR = 'POST_LIKE_ERROR';