export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_LOADING = 'GET_USER_INFO_LOADING';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

export const GET_USER_PROFILE_INFO_BANNER_SUCCESS = "GET_USER_PROFILE_INFO_BANNER_SUCCESS";
export const GET_USER_PROFILE_INFO_BANNER_LOADING = "GET_USER_PROFILE_INFO_BANNER_LOADING";
export const GET_USER_PROFILE_INFO_BANNER_ERROR = "GET_USER_PROFILE_INFO_BANNER_ERROR";

export const GET_USER_PROFILE_INFO_BADGE_SUCCESS = "GET_USER_PROFILE_INFO_BADGE_SUCCESS";
export const GET_USER_PROFILE_INFO_BADGE_LOADING = "GET_USER_PROFILE_INFO_BADGE_LOADING";
export const GET_USER_PROFILE_INFO_BADGE_ERROR = "GET_USER_PROFILE_INFO_BADGE_ERROR";

export const GET_USER_PROFILE_INFO_ITEM_SUCCESS = "GET_USER_PROFILE_INFO_ITEM_SUCCESS";
export const GET_USER_PROFILE_INFO_ITEM_LOADING = "GET_USER_PROFILE_INFO_ITEM_LOADING";
export const GET_USER_PROFILE_INFO_ITEM_ERROR = "GET_USER_PROFILE_INFO_BADGE_ERROR";